### ISSUE TITLE
Add id to {$ref} nodes in network.geojson

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/hobbes-network-format#2]
@jrmerz I see that we are sort of overloading our $ref nodes, but in our network.geojson file, what do you thing about: 

``` js
{
      "$ref": "wwp204-hgr08/link.geojson",
      "type": "link"
      "id": "wwp204-hgr08"
},
```

That way if we were lazy on the crawler, we wouldn't need to parse any files unless they were requested.
So a command like below, wouldn't crawl anything but the one direcotry? 

``` bash
prm show wwp204-hgr08
```

**Comment by jrmerz** [comment]
and id is specified by the given 'id' property.  Which is either properties.id or the identifier given in the conf file?

**Comment by qjhart** [comment]
Yeah, either or.  I was thinking we'd call it `id` all the time, and use the same conf.json file mapping 

``` js
conf.json:={
 "id":"prmname"    # Still called id in {$ref} object
 "regionId":"name"
}
```

**Comment by jrmerz** [comment]
Couple comments.

1) The region information for a node requires region information to first be parsed.
2) Given a link, origin and terminus nodes must be parsed for geometry creation.  This lookup is based on id not node folder name and folder name is not always the same as node id, as is the case with calvin data.  So, for links an entire scan would be required or we parse the nodes/links on initial scan/index creation and store the node id from the geojson as the id instead of the filename.

Either way, both conditions will require a substantial re-write of the /lib/crawler/network.js file for the performance benefit.

Thoughts?

**Comment by qjhart** [comment]
Not sure I understand.  The idea would be to yes, store the real (non-filename) id as in the above examples.  Then I guess to expand a link you would:
- get ref from geojson for that link
- read an parse region info if not there
- read it,  for both origin/destination expand if they haven't been,

Whether it's worth it or not, I will leave to you.  Most important is to parse without csv lookup, and have ability to expand on a per node/link basis.

**Comment by jrmerz** [comment]
I agree with your order of importance.  While we will get a performance gain, with a dataset the size of calvin it will be minimal.  I will add the expand function first.

So currently

``` js
var crawler = require('hobbes-network-format'); // this returns a function
```

will become

``` js
var hnf = require('hobbes-network-format'); // return an object
```

where hnf has two methods (currently).  crawl() & expand()

**Comment by qjhart** [comment]
OK, and these will be callbacks and not promises?
Can expand be a single node or an array of nodes?
I guess in terms of what to expand, we had some ideas, but not completely baked.  We could have mongo style?  hnf.expand(node,{inflows:1}) where hnf.expand(node) expands everything?
